---
- name: Generate and Install Configuration File
  hosts:
    - all
  roles:
    - Juniper.junos
    - snmp
  connection: local
  gather_facts: no

  vars:
    config_assemble: "{{ user_data_path }}/config/{{ inventory_hostname }}"
    config_assemble_build: "{{ config_assemble }}/build"
    config_file: "{{ config_assemble }}/snmp.conf"
    playbook_name: snmp-settings.yaml
    connection_settings:
      host: "{{ ansible_host }}"
      timeout: 120

  pre_tasks:
    - name: confirm or create device config directory
      file:
        path: "{{ config_assemble }}"
        state: directory

    - name: delete previous build directory
      file:
        path: "{{ config_assemble_build }}"
        state: absent

    - name: create build directory
      file:
        path: "{{ config_assemble_build }}"
        state: directory

  tasks:
    - name: assemble config fragments
      assemble:
        src: "{{ config_assemble_build }}"
        dest: "{{ config_file }}"
      notify: install config onto device

  handlers:
    - name: install config onto device
      juniper_junos_config:
        provider: "{{ connection_settings }}"
        src: "{{ config_file }}"
        load: replace
        confirmed: 5
        diff: yes
        ignore_warning: yes
        comment: "playbook {{ playbook_name }}, commit confirmed"
      notify: confirm commit

    - name: confirm commit
      juniper_junos_config:
        provider: "{{ connection_settings }}"
        commit: yes
        comment: "playbook {{ playbook_name }}, confirming previous commit"
