---
- name: Get LLDP neighbor information
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    connection_settings:
      host: "{{ ansible_host }}"

  tasks:
    - name: get lldp neighbor table
      juniper_junos_rpc:
        provider: "{{ connection_settings }}"
        rpcs: get-lldp-interface-neighbors-information
        kwargs:
          interface_name: "{{ item }}"
        format: xml
      loop: "{{ aja2_host.uplinks }}"
      register: lldp

    - name: display lldp neighbor data
      debug:
        var: lldp
        # var: item.stdout_lines
        # msg: "{{ item.stdout_lines }}"
      # loop: "{{ lldp.results }}"
      # loop_control:
      #   label: "{{ item.item }}"
