---
- name: Get device uptime
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars_prompt:
    - name: username
      prompt: Junos Username
      private: no

    - name: password
      prompt: Junos Password
      private: yes

  tasks:
    - name: show ansible_host in verbose mode
      debug:
        var: ansible_host
        verbosity: 1

    - name: get uptime using galaxy module
      juniper_junos_command:
        commands:
          - show system uptime
        provider:
          host: "{{ ansible_host }}"
          port: 22
          user: "{{ username }}"
          passwd: "{{ password }}"
      register: uptime

    # - name: display uptimes (Python style)
    #   debug:
    #     var: uptime['stdout_lines']

    - name: display uptimes (Ansible shortcut)
      debug:
        var: uptime.stdout_lines
