---
- name: Generate and Install Configuration File
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    tmp_dir: "tmp"
    conf_file: "{{ tmp_dir}}/{{ inventory_hostname }}.conf"

  vars_prompt:
    - name: username
      prompt: Junos Username
      private: no

    - name: password
      prompt: Junos Password
      private: yes

  tasks:
    - name: confirm or create configs directory
      file:
        path: "{{ tmp_dir }}"
        state: directory
      run_once: yes

    - name: save device information using template
      template:
        src: template/base-settings.j2
        dest: "{{ conf_file }}"

    - name: install generated configuration file onto device
      juniper_junos_config:
        provider:
          host: "{{ ansible_host }}"
          user: "{{ username }}"
          passwd: "{{ password }}"
          port: 22
          timeout: 120
        src: "{{ conf_file }}"
        load: replace
        comment: "playbook base-settings.yaml"
