---
- name: Install Configuration File
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    connection_settings:
      host: "{{ ansible_host }}"
      timeout: 120

  tasks:
    - name: install set file onto device
      juniper_junos_config:
        provider: "{{ connection_settings }}"
        load: set
        src: "config/ntp.set"
        comment: install-set.yaml playbook -- load ntp.set file

    - name: install set commands onto device
      juniper_junos_config:
        provider: "{{ connection_settings }}"
        load: set
        lines:
          - delete system name-server 198.51.100.100
          - set system name-server 198.51.100.101
        comment: install-set.yaml playbook -- fix name server address
